version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: widen
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"
